#!/bin/bash
#
array=`git diff-index --name-only HEAD`

for name in ${array}
do
    if [[ ! -f $name ]] ; then
       echo "$name is deleted. no need to format"
       continue
    fi  
    extension=${name##*.}
    if [[ ${extension} == "h" || ${extension} == "m" ]];then
      echo "try to format ${name}"
      clang-format -i ${name} -style=file
      if [ $? -eq 0 ]; then
      	echo "clang format ok" ${name}
      else 
        if [[ ${extension} == "m" ]]; then
           echo "clang format object c failed"
      	   exit 1
        fi
      fi
    fi
done